# Generated by Django 3.2.4 on 2021-07-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noobs', '0001_squashed_0013_auto_20210704_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name='task',
            name='until_date',
            field=models.DateField(),
        ),
    ]
